SELECT CS_EXT_TAX, 
CS_ITEM_SK, CS_NET_PAID, CS_PROMO_SK, 
CS_QUANTITY, CS_COUPON_AMT, CS_LIST_PRICE, 
CS_NET_PROFIT, 
CS_SALES_PRICE, CS_BILL_ADDR_SK, CS_ORDER_NUMBER, CS_SHIP_ADDR_SK, CS_SHIP_DATE_SK, CS_SHIP_MODE_SK, 
CS_SOLD_DATE_SK, CS_SOLD_TIME_SK, CS_WAREHOUSE_SK, CS_BILL_CDEMO_SK, CS_BILL_HDEMO_SK, CS_EXT_SHIP_COST, CS_SHIP_CDEMO_SK, CS_SHIP_HDEMO_SK, CS_CALL_CENTER_SK, CS_EXT_LIST_PRICE, CS_WHOLESALE_COST, CS_CATALOG_PAGE_SK, CS_EXT_SALES_PRICE, 
CS_BILL_CUSTOMER_SK, CS_EXT_DISCOUNT_AMT, CS_NET_PAID_INC_TAX, CS_SHIP_CUSTOMER_SK, CS_NET_PAID_INC_SHIP, CS_EXT_WHOLESALE_COST, CS_NET_PAID_INC_SHIP_TAX