[snowflake]
user="wcd_midterm_load_user"
password="wcdmidtermloaduser1234"
account="A******-J******"
warehouse="compute_wh"
database="tpcds"
schema="raw"
role="accountadmin"
stage="inventory_stage"
table="inventory"

[s3]
bucket="de-materials-tpcds"
key="inventory.csv"

[aws]
aws_access_key_id="******"
aws_secret_access_key="******"